macos: use /tmp instead of /dev/shm
commaai/cereal pull request #635
Opened 2024-11-24 12:00 UTC by devtekve

In macos a lot of the tests in OP still seem to rely on "/dev/shm" so this, alongside with https://github.com/commaai/openpilot/pull/34097 should unblock those cases

2024-11-28 19:03 UTC, adeebshihadeh requested changes
Can you pull this out into a constant to reduce all the ifdef everywhere?

2024-12-04 20:27 UTC, devtekve commented
I will , sorry ! I’ve been busy with MADS rewrite in SP

2024-12-10 21:36 UTC, adeebshihadeh requested changes

2024-12-10 21:36 UTC, adeebshihadeh commented on msgq/msgq_tests.cc
> +
revert this

2024-12-10 21:36 UTC, adeebshihadeh commented on msgq/event.cc
> +  #endif
this should be pulled out

2024-12-10 21:36 UTC, adeebshihadeh commented on msgq/msgq.cc
> +    std::string full_path = "/dev/shm/";
same here

2024-12-10 21:37 UTC, adeebshihadeh commented
`/dev/shm` and `/tmp` should only be defined once

2025-12-28 08:13 UTC, closed without merging